bvc/urls.py
from django.conf.urls import url

from . import views

app_name = 'bvc'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^resume-commandes$', views.send_command_summary, name='send_command_summary'),
    url(r'^rappel-mail$', views.subscribe_to_reminder, name='subscribe_to_reminder'),
    url(r'^commande-commission$', views.place_commission_command,
        name='place_commission_command'),
    url(r'^rappel-annulation-commande$', views.contact_unsold_commands,
        name='contact_unsold_commands'),
    url(r'^tableau-commandes-preparees$', views.print_prepared_commands,
        name='print_prepared_commands'),
]

gucem/urls.py
from django.conf.urls import include, url

from bvc.admin.site import admin_site

urlpatterns = [
    url(r'^', include('bvc.urls')),
    url(r'^admin/', admin_site.urls),
]

bvc/models/individual_command.py
from django.db import models
from django.utils.timezone import now
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string

from .command import *
from .configuration import get_config
from . import validators
from . import voucher

from .. import utils


class IndividualCommand(models.Model):
    """Represent a command placed to the manager."""
    amount = models.PositiveSmallIntegerField( # Amount before reduction
        blank=False, null=False,
        validators=[validators.validate_voucher_amount_multiple],
        verbose_name='montant',
        help_text='Avant réduction.',
    )
    datetime_placed = models.DateTimeField(auto_now_add=True, verbose_name='date')
    datetime_prepared = models.DateField(null=True, blank=True, verbose_name='date de préparation',)
    datetime_cancelled = models.DateField(null=True, blank=True, verbose_name="date d'annulation",)
    # To make packets with high-value vouchers only.
    # For intance, if a member places a command to buy a 500-euro object, we can
    # give him 10 vouchers of 50 euros (he does not need 10-euro or 20-euro vouchers).
    spent_at_once = models.BooleanField(default=False, verbose_name='dépensée en une fois',)

    class Meta:
        abstract = True

    @classmethod
    def get_total_amount(cls, states):
        total = cls.objects.filter(state__in=states).aggregate(models.Sum('amount'))['amount__sum']
        return total or 0

    @property
    def voucher_distrib(self):
        return voucher.get_distrib(self.amount, self.spent_at_once)

    @property
    def n_vouchers_10(self):
        return self.voucher_distrib[10]

    @property
    def n_vouchers_20(self):
        return self.voucher_distrib[20]

    @property
    def n_vouchers_50(self):
        return self.voucher_distrib[50]

    @property
    def email(self):
        raise NotImplementedError()

    # Define this property in the abstract class to have a common interface for
    # the templates
    @property
    def price(self):
        return 0

    def amount_changed(self, old_amount):
        if old_amount == self.amount:
            return

        voucher.update_stock(old_amount - self.amount, str(self))
    
    def send_preparation_email(self):
        send_mail(
            utils.format_mail_subject('Commande en cours de préparation'),
            render_to_string(
                'bvc/mails/command_being_prepared.txt',
                {
                    'amount': self.amount,
                    'price': self.price,
                }
            ),
            get_config().bvc_manager_mail,
            [self.email],
        )

    def prepare(self):
        if self.state != TO_BE_PREPARED_STATE:
            raise InvalidState(
                "La commande {} n'est pas dans le bon état pour être préparée.".format(self)
            )

        voucher.update_stock(-self.amount, str(self))        

        self.state = PREPARED_STATE
        self.datetime_prepared = now()
        self.save()

        send_mail(
            utils.format_mail_subject('Commande reçue'),
            render_to_string(
                'bvc/mails/command_prepared.txt',
                {
                    'amount': self.amount,
                    'price': self.price,
                }
            ),
            get_config().bvc_manager_mail,
            [self.email],
        )

    def warn_about_cancellation(self):
        if self.state != PREPARED_STATE:
            raise InvalidState("La commande {} n'est pas préparée, impossible "
                               "de prévenir son annulation.".format(self))

        send_mail(
            utils.format_mail_subject('Commande bientôt annulée'),
            render_to_string(
                'bvc/mails/cancel_command_soon.txt',
                {'cmd': self, 'grouped_command_day': get_config().grouped_command_day}
            ),
            get_config().bvc_manager_mail,
            [self.email],
        )

    def cancel(self):
        if self.state not in [PLACED_STATE, TO_BE_PREPARED_STATE, PREPARED_STATE]:
            raise InvalidState("La commande {} n'est pas dans le bon état pour être annulée.".format(self))

        if self.state == PREPARED_STATE:
            voucher.update_stock(self.amount, str(self))

        self.state = CANCELLED_STATE
        self.datetime_cancelled = now()
        self.save()

        send_mail(
            utils.format_mail_subject('Commande annulée'),
            render_to_string(
                'bvc/mails/cancel_command.txt',
                {
                    'amount': self.amount,
                    'date': self.datetime_placed,
                }
            ),
            get_config().bvc_manager_mail,
            [self.email],
        )

    def uncancel(self):
        if self.state != CANCELLED_STATE:
            raise InvalidState("La commande {} n'est pas dans le bon état pour être désannulée.".format(self))

        self.state = PLACED_STATE
        datetime_cancelled = self.datetime_cancelled
        self.datetime_cancelled = None
        self.save()

        send_mail(
            utils.format_mail_subject('Commande désannulée'),
            render_to_string(
                'bvc/mails/uncancel_command.txt',
                {
                    'amount': self.amount,
                    'cancel_date': datetime_cancelled,
                }
            ),
            get_config().bvc_manager_mail,
            [self.email],
        )

bvc/models/user.py
from django.db import models
from django.conf import settings
from django.template.loader import render_to_string

from .configuration import get_config
from .. import utils


class AbstractUser(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name='utilisateur', on_delete=models.CASCADE,)
    receive_reminder = models.BooleanField(
        default=False,
        verbose_name='reçoit le mail de rappel',
    )

    class Meta:
        abstract = True

    def send_command_summary(self):
        self.user.email_user(
            utils.format_mail_subject('Vos commandes en cours'),
            render_to_string(
                'bvc/mails/command_summary.txt',
                {'commands': self.commands.all()}
            ),
            get_config().bvc_manager_mail
        )

    def remind_next_grouped_command(self):
        self.user.email_user(
            utils.format_mail_subject('La date limite de commande approche'),
            render_to_string(
                'bvc/mails/remind_next_grouped_command.txt',
                {'day': get_config().grouped_command_day - 1}
            ),
            get_config().bvc_manager_mail
        )


class Member(AbstractUser):
    ESMUG = 'esmug'
    GUCEM = 'gucem'

    CLUB_CHOICES = (
        (GUCEM, 'GUCEM'),
        (ESMUG, 'ESMUG'),
    )

    license = models.CharField(max_length=12, unique=True, verbose_name='licence CAF',)
    club = models.CharField(
        max_length=max(len(choice[0]) for choice in CLUB_CHOICES),
        choices=CLUB_CHOICES,
        default=GUCEM,
        verbose_name='club',
    )

    class Meta:
        verbose_name = 'adhérent'

    def __str__(self):
        return '{} {} - {}'.format(
            self.user.first_name,
            self.user.last_name,
            self.user.email,
        )


class Commission(AbstractUser):
    class Meta:
        verbose_name = 'commission'

    def __str__(self):
        return self.user.username

bvc/forms/bank_deposit.py
from django import forms
from django.conf import settings

from .. import models


class BankDepositAdminForm(forms.ModelForm):
    class Meta:
        model = models.BankDeposit
        exclude = ['made']


class CheckBankDepositAdminForm(forms.ModelForm):
    class Meta:
        model = models.CheckBankDeposit
        fields = ['bank_deposit']
    
    def save(self, commit=True):
        instance = super().save(commit=False)
        models.member_command.bank_commands(
            models.command.CHECK_PAYMENT,
            self.cleaned_data['bank_deposit']
        )

        if commit:
            instance.save()

        return instance


class CashBankDepositAdminForm(BankDepositAdminForm):
    n10 = forms.IntegerField(
        min_value=0,
        label='Nombre de billets de 10',
    )
    n20 = forms.IntegerField(
        min_value=0,
        label='Nombre de billets de 20',
    )
    n50 = forms.IntegerField(
        min_value=0,
        label='Nombre de billets de 50',
    )
    amount = forms.IntegerField(
        disabled=True,
        required=False,
        label='Total',
    )

    def __init__(self, *args, **kwargs):
        instance = kwargs.get('instance', None)

        if instance:
            kwargs.update(initial={
                'amount': instance.total_price
            })
        super().__init__(*args, **kwargs)

    class Meta:
        model = models.CashBankDeposit
        fields = ['bank_deposit', 'n10', 'n20', 'n50', 'amount',]

    def get_amount(self):
        return sum(self.cleaned_data['n' + str(n)] * n for n in (10, 20, 50))

    def clean(self):
        cleaned_data = super().clean()
        try:
            amount = self.get_amount()
        except KeyError:
            return

        if models.member_command.get_available_cash_amount() - amount < 0:
            raise forms.ValidationError("Il n'y a pas autant d'argent liquide à disposition.")

        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)

        treasury = models.treasury.get_treasury()
        amount = self.get_amount()
        total = models.member_command.get_available_cash_amount()
        treasury_delta = total - treasury - amount

        # Create the treasury operation
        instance.treasury_operation = models.treasury.treasury_op_from_delta(
            treasury_delta,
            'BVE {}'.format(models.CashBankDeposit.next_id()),
        )

        models.member_command.bank_commands(
            models.command.CASH_PAYMENT,
            self.cleaned_data['bank_deposit']
        )

        if commit:
            instance.save()

        return instance

bvc/forms/command.py
from django import forms
from django.utils.timezone import now

from .. import models


class GroupedCommandAdminForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        try:
            self.fields['datetime_received'].required = True
        except KeyError:
            pass
        try:
            self.fields['datetime_prepared'].required = True
        except KeyError:
            pass

    class Meta:
        model = models.GroupedCommand
        fields = ['state', 'datetime_placed', 'placed_amount', 'datetime_received',
                  'received_amount', 'datetime_prepared', 'prepared_amount',]

    def clean_amount_field(self, state, prev_state):
        amount = self.cleaned_data[state + '_amount']

        if not amount:
            raise forms.ValidationError('The amount cannot be zero.')

        prev_amount = self.instance.__dict__[prev_state + '_amount']
        if amount > prev_amount:
            raise forms.ValidationError(
                'The {} amount cannot be greater than '
                'the {} amount.'.format(state, prev_state)
            )

        self.amount = amount
        return amount

    def clean_date_field(self, state, prev_state):
        date = self.cleaned_data['datetime_' + state]

        prev = self.instance.__dict__['datetime_' + prev_state]
        try:
            prev_date = prev.date()
        except AttributeError:
            prev_date = prev

        if date < prev_date:
            raise forms.ValidationError(
                'The {} date cannot be older than '
                'the {} date.'.format(state, prev_state)
            )

        self.date = date
        return date

    def check_state(self, state, callback):
        if self.instance.__dict__['state'] != state:
            raise forms.ValidationError("La commande n'est pas dans le bon état.")

        self.callback = callback

    def clean_placed_amount(self):
        unprepared_cmd = models.GroupedCommand.objects.exclude(
            state=models.command.PREPARED_STATE
        )
        if unprepared_cmd.count():
            raise forms.ValidationError("Une commande groupée est déjà en cours.")
        
        self.callback = self.instance.place
        self.date = now()
        self.amount = self.cleaned_data['placed_amount']

        return self.amount

    def clean_received_amount(self):
        self.check_state(models.command.PLACED_STATE, self.instance.receive)
        return self.clean_amount_field('received', 'placed')

    def clean_datetime_received(self):
        self.check_state(models.command.PLACED_STATE, self.instance.receive)
        return self.clean_date_field('received', 'placed')

    def clean_prepared_amount(self):
        self.check_state(models.command.RECEIVED_STATE, self.instance.prepare_)
        return self.clean_amount_field('prepared', 'received')

    def clean_datetime_prepared(self):
        self.check_state(models.command.RECEIVED_STATE, self.instance.prepare_)
        return self.clean_date_field('prepared', 'received')

    def save(self, commit=True):
        instance = super().save(commit=False)
        self.callback(self.amount, self.date)

        if commit:
            instance.save()

        return instance


class PlaceMemberCommand(forms.ModelForm):
    class Meta:
        model = models.MemberCommand
        fields = ['amount', 'comments',]


class PlaceCommissionCommand(forms.ModelForm):
    commission = forms.ModelChoiceField(
        queryset=models.user.Commission.objects,
        empty_label=None,
    )

    class Meta:
        model = models.CommissionCommand
        fields = ['commission', 'amount', 'reason', 'comments',]

bvc/forms/commission_command.py
from django import forms

from .. import models


class PlaceCommissionCommand(forms.ModelForm):
    commission = forms.ModelChoiceField(
        queryset=models.user.Commission.objects,
        empty_label=None,
    )

    class Meta:
        model = models.CommissionCommand
        fields = ['commission', 'amount', 'reason', 'spent_at_once',]


class CommissionCommandAdminForm(forms.ModelForm):
    class Meta:
        model = models.CommissionCommand
        fields = ['commission', 'state', 'amount', 'reason', 'spent_at_once',
                   'datetime_prepared', 'datetime_cancelled', 'datetime_given',]

    def clean_amount(self):
        amount = self.cleaned_data['amount']

        if not amount:
            raise forms.ValidationError('The amount cannot be zero. Instead, cancel the command.')

        if (self.instance.state != models.command.PLACED_STATE and
            self.instance.state != models.command.TO_BE_PREPARED_STATE and
            self.instance.state != models.command.RECEIVED_STATE and
            self.instance.state != models.command.PREPARED_STATE):
           raise forms.ValidationError('The amount cannot be changed due to the command state.')

        self.old_amount = self.instance.amount

        if not models.voucher.is_delta_valid(self.old_amount - amount):
            raise forms.ValidationError("You don't have enough vouchers.")

        return amount

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.amount_changed(self.old_amount)

        if commit:
            instance.save()

        return instance

bvc/forms/member_command.py
from django import forms

from .. import models


class PlaceMemberCommand(forms.ModelForm):
    class Meta:
        model = models.MemberCommand
        fields = ['amount', 'spent_at_once',]


class MemberCommandAdminForm(forms.ModelForm):
    class Meta:
        model = models.MemberCommand
        fields = ['member', 'state', 'amount', 'spent_at_once',
                   'datetime_prepared', 'datetime_cancelled', 'datetime_sold',
                   'payment_type', 'bank_deposit',]

    def clean_amount(self):
        amount = self.cleaned_data['amount']

        if not amount:
            raise forms.ValidationError('The amount cannot be zero. Instead, cancel the command.')

        if (self.instance.state != models.command.PLACED_STATE and
            self.instance.state != models.command.TO_BE_PREPARED_STATE and
            self.instance.state != models.command.RECEIVED_STATE and
            self.instance.state != models.command.PREPARED_STATE):
           raise forms.ValidationError('The amount cannot be changed due to the command state.')

        self.old_amount = self.instance.amount

        if not models.voucher.is_delta_valid(self.old_amount - amount):
            raise forms.ValidationError("You don't have enough vouchers.")

        return amount

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.amount_changed(self.old_amount)

        if commit:
            instance.save()

        return instance

bvc/templates/bvc/bank_deposit.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Dépôt en banque{% endblock %}

{% block contents %}
TODO
{% endblock %}

bvc/templates/bvc/command_commission.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Commandes BVC commission{% endblock %}

{% block contents %}
<p>Commandes commissions</p>
{% endblock %}

bvc/templates/bvc/command_member.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Commandes BVC adhérent{% endblock %}

{% block contents %}
<h2>Commandes adhérents</h2>

<form action="{% url 'bvc:command_member' %}" method="POST">
  {% csrf_token %}
  
  <table>
    {{ form.as_table }}
  </table>
  
  <input type="submit" value="Commander" />
</form>
{% endblock %}

bvc/templates/bvc/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}BVC{% endblock %}

{% block contents %}
<h2>Bons Vieux Campeur au GUCEM</h2>

<h3>Ce site est obsolète. Nouveau site : <a href="https://gucem.williamchevremont.be/">https://gucem.williamchevremont.be/</a></h3>

<p>
  Questions : <strong>{{ bvc_manager_mail }}</strong>
</p>

<!--

<p>
  Tu peux recevoir par mail la liste de tes commandes en cours en remplissant
  ce formulaire :

<form action="{% url 'bvc:send_command_summary' %}" method="POST">
  {% csrf_token %}
  {{ command_summary_form }}
  <input type="submit" value="Envoyer" />
</form>
</p>

<h3>Modalités</h3>

<p>
  Pour commander des bons Vieux Campeur (BVC) il suffit de
  remplir le formulaire en bas de page.
  Tu recevras alors un mail lorsqu'elle sera
  disponible.
</p>

<p>
  La <strong>distribution</strong> des bons se fait
  durant la <a href="https://www.esmug-gucem.fr/gucem/contact/"><strong>permanence du mardi</strong></a>. Tu peux régler en <strong>chèque</strong> (plus simple pour nous) ou <strong>espèces</strong> (merci
  de préparer l'appoint) le montant après réduction (GUCEM : <strong>{{ gucem_discount }}%</strong> - ESMUG : <strong>{{ esmug_discount }}%</strong>) et
  récupérer des bons que tu peux donner directement au magasin en guise de
  paiement. Si tu préviens au préalable par mail le responsable des bons, une
  personne autre que toi peut <strong>passer à ta place</strong>. Les bons sont <strong>valables un an</strong>.
</p>

<p>
  Les commandes sont <strong>mensuelles</strong> : si tu commandes tes bons <strong>avant le {{ last_day_to_command }} au soir</strong>, tu les recevras environ une semaine après cette date limite. Les commandes du mois n non récupérées avant le {{ last_day_to_command }} du mois n+1
  sont <strong>annulées</strong>. Exemples :
  <ul>
    <li>Je commande le <strong>{{ last_day_to_command }} septembre</strong>, je reçois mes bons environ une <strong>semaine</strong> après</li>
    <li>Je commande le <strong>{{ grouped_command_day }} septembre</strong>, je reçois mes bons environ un <strong>mois</strong> après (tu es servi comme les commandes passées en octobre)</li>
    <li>Je commande le <strong>{{ last_day_to_command }} septembre</strong> et <strong>ne passe pas</strong> chercher mes bons <strong>avant le {{ last_day_to_command }} octobre</strong>, ma commande est <strong>annulée</strong></li>
  </ul>
</p>

<p>
  En renseignant ton mail ci-dessous, tu recevras un rappel quelques jours avant
  la date limite de commande. Si c'est déjà le cas, l'envoi du formulaire
  désactive les rappels.
</p>

<form action="{% url 'bvc:subscribe_to_reminder' %}" method="POST">
  {% csrf_token %}
  {{ grouped_cmd_reminder_form }}
  <input type="submit" value="Envoyer" />
</form>
</p>

<p>
  Le magasin <strong>ne rend pas la monnaie</strong>. Nous dosons donc
  les bons de 10, 20 et 50 euros pour que tu puisses approcher au plus près du prix de ton achat
  sans pour autant avoir des paquets (de bons) énormes. Néanmoins,
  si tu connais d'avance les <strong>dépenses faites
  en une seule fois</strong> au magasin, merci de passer une commande pour chacune
  et de cocher
  la case correspondante dans le formulaire. Ainsi, nous savons que nous pouvons
  te donner 8 bons de 50 plutôt que 40 bons de 10 pour une dépense de 400 euros, ce qui est bien sûr plus
  pratique. Exemples :
  <ul>
    <li>Je commande pour acheter <strong>en une fois</strong> un ou plusieurs objet(s), je passe <strong>une</strong> commande et <strong>coche</strong> la case</li>
    <li>Je commande pour acheter <strong>en plusieurs fois</strong> deux objets (donc un à chaque fois), je passe <strong>deux</strong> commandes et <strong>coche</strong> la case pour chacune</li>
    <li>Je commande mais ignore comment je vais dépenser mes bons, je passe <strong>une</strong> commande et <strong>ne coche pas</strong> la case</li>
  </ul>

  Dans le doute, <strong>ne coche pas</strong> la case. Elle sert juste à nous
  simplifier le travail.
</p>

<h3 id="passer-commande">Passer commande</h3>

Après la commande, <strong>un mail de confirmation est envoyé</strong>. Si tu ne le reçois pas,
passe commande à {{ bvc_manager_mail }}.

<p>
  Si tu es une <strong>commission</strong>, merci de commander sur
  <a href="{% url 'bvc:place_commission_command' %}">cette page</a>.
  Pour les <strong>adhérents</strong>, c'est ici :
</p>

<form action="{% url 'bvc:home' %}" method="POST">
  {% csrf_token %}
  
  <table>
    {{ user_form.as_table }}
    {{ member_form.as_table }}
    {{ command_form.as_table }}
  </table>
  
  <input type="submit" value="Commander" />
</form>
-->
{% endblock %}

{% block javascript %}
<!--
<script
  src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g="
  crossorigin="anonymous"></script>

<script>
$( document ).ready(function() {
    var ESMUG_DISCOUNT = 0.18;
    var GUCEM_DISCOUNT = ESMUG_DISCOUNT;
    var amountInput = $('#id_amount');
    var clubInput = $('#id_club');

    // Create price HTML element
    var td = amountInput.closest('td');
    td.append('<div class="price"></div>');
    var priceDiv = td.find('.price');

    function getDiscount() {
        var club = clubInput.val();

        if (club == 'esmug')
            return ESMUG_DISCOUNT;
        else if (club == 'gucem')
            return GUCEM_DISCOUNT;
        throw 'Unknown club ' + club;
    }

    function displayPrice(price) {
        priceDiv.html('Soit <strong>' + price + '</strong> euros à payer.');
    }

    function computePrice() {
        var amount = parseInt(amountInput.val()) || 0;
        return ((1 - getDiscount()) * amount).toFixed(2);
    }

    amountInput.blur(function(e) {
        displayPrice(computePrice());
    });

    clubInput.change(function(e) {
        displayPrice(computePrice());
    });

    displayPrice(computePrice());
});
</script>
-->
{% endblock %}

bvc/templates/bvc/place_commission_command.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Commandes BVC commission{% endblock %}

{% block contents %}
<h1>Commande de bons Vieux Campeur pour les commissions</h1>

<p>
  Si tu es un adhérent, merci de commander <a href="{% url 'bvc:home' %}#passer-commande">ici</a>.
</p>

<p>
  <a href="{% url 'bvc:home' %}">Retour à la page des bons</a>
</p>

<form action="{% url 'bvc:place_commission_command' %}" method="POST">
  {% csrf_token %}
  
  <table>
    {{ form.as_table }}
  </table>
  
  <input type="submit" value="Commander" />
</form>
{% endblock %}

bvc/templates/bvc/print_prepared_commands.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Commandes BVC préparées{% endblock %}

{% block style %}
<style>
  table {
    border-collapse: collapse;
    margin-bottom: 10px;
  }

  td, th {
    border: 1px solid #000;
    padding: 5px;
  }
</style>
{% endblock %}

{% block contents %}
{% if member_commands.count %}
  <table>
    <tr>
      <th>Nom</th>
      <th>Prénom</th>
      <th>Num</th>
      <th>Bons</th>
      <th>Prix</th>
      <th>En 1</th>
      <th>10</th>
      <th>20</th>
      <th>50</th>
      <th colspan="3">Paiement</th>
    </tr>

  {% for cmd in member_commands %}
    <tr>
      <td>{{ cmd.member.user.last_name }}</td>
      <td>{{ cmd.member.user.first_name }}</td>
      <td><strong>{{ cmd.id|add:neg_min_member_cmd_id }}</strong></td>
      <td>{{ cmd.amount }}</td>
      <td>{{ cmd.price }}</td>
      <td style="text-align: center;">{% if cmd.spent_at_once %} X {% endif %}</td>
      <td>{{ cmd.n_vouchers_10 }}</td>
      <td>{{ cmd.n_vouchers_20 }}</td>
      <td>{{ cmd.n_vouchers_50 }}</td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  {% endfor %}
  </table>
{% endif %}

{% if commission_commands.count %}
  <table>
    <tr>
      <th>Commission</th>
      <th>Bons</th>
      <th colspan="3">Distribuée</th>
    </tr>

  {% for cmd in commission_commands %}
    <tr>
      <td>{{ cmd.commission.user.username }}</td>
      <td>{{ cmd.amount }}</td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  {% endfor %}
  </table>
{% endif %}
{% endblock %}